### ISSUE TITLE
(Firefox) The default context menu item is appearing on selections' and images' context menus

### ISSUE THREAD

**Issue by leakymemory** [OneNoteDev/WebClipper#6]
1) In Firefox, select some text and right click, or right click an image

**Expected:** The default context menu item 'OneNote Web Clipper' is not in the context menu
**Actual:** The default context menu item is there

(from VishaalK): According to https://bugzilla.mozilla.org/show_bug.cgi?id=1274860 this is a known bug and someone was working on it in July. It was updated on 8/10. Not sure if Mozilla employees are going to fix this or if its left for someone else to do. I posted a comment asking for an update.

**Comment by mttwc** [comment]
Marking this as external as it is out of our control (it's a bug on the Firefox side that we can't work around). Will leave this issue open so we can at least track its existence.

**Comment by iconix** [comment]
This bug is also being tracked here more actively: https://bugzilla.mozilla.org/show_bug.cgi?id=1275126

The fix was accepted. Verified it works in Firefox Developer Edition 51.0a2 (2016-10-04) (32-bit)

![image](https://cloud.githubusercontent.com/assets/1144401/19090710/79d6c048-8a34-11e6-8ed5-06434b6d0ef0.png)

However, my regular Firefox still won't let me update past 47.0.1 for some reason :( Can someone else verify the fix in regular Firefox before closing this out?

**Comment by mttwc** [comment]
@iconix That seems to be a different issue. On 52 I still get this issue where the OneNote Web Clipper context menu action shows up in addition to selections and image clipping.

**Comment by mttwc** [comment]
Looks like this Firefox is raising this from the dead :P

https://hg.mozilla.org/mozilla-central/rev/49d1c7361c57

**Comment by mttwc** [comment]
Firefox has fixed this as of 53.0a1 nightly.
