### ISSUE TITLE
When we hit errors, they are recorded/counted many times

### ISSUE THREAD

**Issue by leakymemory** [OneNoteDev/WebClipper#89]
In looking through the logs, particularly when we hit an unexpected failure, we are logging in such a way that a single failure can be logged/counted multiple times.  This makes it hard to monitor spikes as a small number of errors can seem more magnified.

Session_Id == "127f0021-947d-0efa-474d-fb9cb50e952a" as an example.

**Comment by iconix** [comment]
For the session provided, the failure overlap is between the `FetchNonLocalData`, `GetLocalizedStrings`, and `InvokeTooltip` events.

I'd actually argue that the fact that all three fired in this session provides useful information... this helps validate a hypothesis that has been floating around since we launched "What's New" and Tooltips: our recent spike in `GetLocalizedStrings` failures is due to these features increasing the raw number of these network calls (without increasing the % failure rate). We need all three events to be able to say that because:
- If `FetchNonLocalData` didn't fire, this would suggest we are actually failing to pull the strings from local storage.
- If `GetLocalizedStrings` didn't fire, this would suggest some other network fetch for data is what actually fails (e.g., `GetFlightingAssignments`)
- If `InvokeTooltip` (and `InvokeWhatsNew`) didn't fire, this would suggest that our theory that these new features has caused the persistent spike in `GetLocalizedStrings` failures is incorrect - and that we probably just happened to introduce a bug at the same time as these feature launches.

So without any one of these events, we'd lose debugging information...

@leakymemory @mttwc I wasn't around for the original discussion that opened this issue- thoughts on this? What would be the ideal resolution to this issue in your minds? Thanks!

**Comment by iconix** [comment]
Ah, looking closer, we could remove the `GetLocalizedStrings` event (and all other events that wrap a call to `FetchNonLocalData`) because we log the `Key` property on `FetchNonLocalData` (which has values like `locStrings`, `flightingInfo`).

The trade-off would be that we'd always need to fire up Kusto in order to tell which kind of nonlocal data call failed. I also feel like we'd probably still want to alert if a particular nonlocal data call is failing more than the others.

**Comment by mttwc** [comment]
I think we should keep all of them as failures, however we need to adjust our dashboards to not visualize things such as "count the number of all failures" because it leads to misleading numbers.

**Comment by mttwc** [comment]
As discussed this morning, we find that logging failures at different levels of abstraction is useful, but we need to rework our reporting. I'll be working on this.
